FROM php:8.2-apache

RUN a2enmod rewrite

WORKDIR /var/www/html

RUN echo "session.cookie_httponly = 1" >> /usr/local/etc/php/conf.d/session.ini
RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www/html

EXPOSE 80
CMD ["apache2-foreground"]
